import "react-toastify/dist/ReactToastify.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "./components/ToastProvider";
import { UserProvider } from "./context/UserContext";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <UserProvider>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div className="absolute top-0 z-50 w-full">
        <Navbar/>
      </div>
        <ToastProvider/>
        {children}
      </body>
        </UserProvider>
    </html>
  );
}
